name: 'Install k8s dependencies'
description: 'Install k8s dependencies'

inputs:
  token:
    description: 'github token'
    required: true
  cloneTools:
    description: 'check if downloads'
    required: false
    default: 'true'
  namespace:
    description: ''
    required: false
    default: 'default'
  version:
    description: ''
    required: false
    default: '0.0.1'
  repository:
    description: ''
    required: false
    default: 'acm-app-repository'
  renderedOutput:
    description: ''
    required: false
    default: ./manifests/k8s-dependencies.yml
  writeSummary:
    required: true
    default: "false"
    description: ""

runs:
  using: "composite"

  steps:

    # pre-job
    - name: Setup | Cloning tools
      uses: actions/checkout@v4
      with:
        token: ${{inputs.token}}
        ref: main
        path: .pipeline
        repository: filipeforattini/ff-iac-github-actions

    - name: Setup | Pipeline config scrapper
      if: inputs.cloneTools != false
      uses: filipeforattini/ff-iac-github-actions/.github/actions/config-scrapper@main
      id: analysis

    # namespace
    - name: K8s create namespace
      shell: bash
      run: kubectl create namespace ${{inputs.namespace}} --dry-run=client --validate=false --output=yaml | kubectl apply -f -

    # dependencies
    - name: Dependencies | Resources render
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      shell: bash
      run: |
        ytt \
          -f ./.pipeline/deploy/as-k8s/dependencies.schema.yml \
          -f ./.pipeline/deploy/as-k8s/dependencies.yml \
          -f ${{steps.analysis.outputs.deploy_dependencies_file}} \
          --data-value repository=${{inputs.repository}} \
            > ${{inputs.renderedOutput}}

    - name: Docs | Outputs dependencies
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      shell: bash
      run: |
        echo -e "<details><summary>📝 Dependencies</summary>\n\n\`\`\`yml \n$(cat ${{inputs.renderedOutput}})\n \`\`\`\n </details>\n\n" >> $GITHUB_STEP_SUMMARY


    - name: Dependencies | Helm update
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      shell: bash
      run: |	
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

    - name: Dependencies | Mysql
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=mysql \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh
        
    - name: Dependencies | Postgres
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=postgres \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | Rabbitmq
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=rabbitmq \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | Elasticsearch
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=elasticsearch \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | Redis
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=redis \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | Nats
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=nats \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | Etcd
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=etcd \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh

    - name: Dependencies | MongoDB
      if: steps.analysis.outputs.feature_has_dependencies == 'true'
      continue-on-error: true
      shell: bash
      run: |	
        K8S_NAMESPACE=${{inputs.namespace}} \
        K8S_REPOSITORY=${{inputs.repository}} \
        DEPENDENCY_NAME=mongodb \
        REPOSITORY_TAG_VERSION=${{inputs.version}} \
        DEPENDENCY_FILE=${{inputs.renderedOutput}} \
          ./.pipeline/src/dependency-install.sh
