const fs = require('fs')
const path = require('path')

module.exports = {
  stub: `
# This file was autogenerated at <%= generatedAt %>.

# Build Step
FROM <%= image %>:<%= tag %> as builder

WORKDIR /svc
COPY . /svc

RUN apk add --no-cache git

RUN go version \
  && <%= dependencyCommand %> \
  && mkdir /svc/out

RUN go build -o ./out/go-app .


# Final step
FROM alpine:3.9 

WORKDIR /svc

RUN apk add ca-certificates

<% labels.length && print("LABEL " + labels.join(' \\\n\t')) %>

<% environmentVariables.length && print("ENV "+ environmentVariables.join(' \\\n\t')) %>

COPY --from=build_base /svc/out/go-app /src/go-app

ENTRYPOINT ["<%= entrypoint %>"]
CMD ["<%= command %>"]
`,

  defaultValues: {
    image: "golang",
    tag: "1.12-alpine",
    labels: ["builder=pipeline"],
    environmentVariables: ["OS=Alpine"],
    dependencyCommand: "go mod download",
    entrypoint: "go-app",
    command: "",
  },

  files: [],
};
