module.exports = {  
  stub: `
# This file was autogenerated at <%= generatedAt %>.
FROM <%= image %>:<%= tag %>

LABEL <%= labels %>

ENV <%= environmentVariables %>

WORKDIR /app
COPY . /app

RUN <%= dependencyCommand %>

ENTRYPOINT ["python"]
CMD ["app.py"]
`,

  defaults: {
    image: 'alpine',
    tag: '17',
    labels: [],
    environmentVariables: [],
    dependencyCommand: [],
    entrypoint: 'npm',
    command: 'start',
  },

  files: []
}
