module.exports = {
  stub: `
# This file was autogenerated at <%= generatedAt %>.
FROM <%= image %>:<%= tag %>

<% labels.length && print("LABEL " + labels.join(' \\\n\t')) %>

<% environmentVariables.length && print("ENV "+ environmentVariables.join(' \\\n\t')) %>

WORKDIR /svc
COPY . /svc

RUN <%= dependencyCommand %>

ENTRYPOINT ["<%= entrypoint %>"]
CMD ["<%= command %>"]
`,

  defaultValues: {
    image: "node",
    tag: "17-alpine",
    labels: ["builder=pipeline"],
    environmentVariables: ["OS=Alpine"],
    dependencyCommand: "npm install",
    entrypoint: "npm",
    command: "start",
  },

  files: [],
};
