# This file was autogenerated at <%= generatedAt %>.
FROM <%= image %>:<%= tag %>

LABEL <%= labels %>

ENV <%= environmentVariables %>

WORKDIR /app
COPY . /app

RUN <%= dependencyCommand %>

ENTRYPOINT ["python"]
CMD ["app.py"]
