module.exports = {  
  stub: `
# This file was autogenerated at <%= generatedAt %>.
FROM <%= image %>:<%= tag %>

LABEL <%= labels %>

ENV <%= environmentVariables %>

WORKDIR /app
COPY . /app

RUN <%= dependencyCommand %>

ENTRYPOINT ["python"]
CMD ["app.py"]
`,

  defaultValues: {
    image: 'python',
    tag: '3.7',
    labels: [],
    environmentVariables: [],
    dependencyCommand: [],
    entrypoint: 'python',
    command: 'app.py',
  },

  files: []
}
