name: 'Generate ReleaseRC file'
description: ''

inputs:
  writeSummary:
    required: false
    default: "false"
    description: ""
  defaultBranch:
    required: true
    default: master
    description: ""
  files:
    required: false
    default: "[]"
    description: ""
  npmPlugin:
    required: false
    default: "false"
    description: ""
  createRelease:
    required: false
    default: "true"
    description: ""
  updateChangelog:
    required: false
    default: "true"
    description: ""

runs:
  using: 'node20'
  main: 'index.js'

