const fs = require("fs");
const _ = require('lodash');
const path = require("path");
const core = require("@actions/core");

const template = _.template(`
# This file was autogenerated at <%= generatedAt %>.
<% _.forEach(globsToIgnore, function(pathy) { %><%- pathy %>\n<% }); %>
`);

async function action() {
  let globsToIgnore = JSON.parse(core.getInput('globsToIgnore', { required: false }))

  const content = template({ 
    generatedAt: new Date().toISOString(),
    'globsToIgnore': [
      '.git',
      '.vscode',
      '.github',
      'manifests',
      ...globsToIgnore,
    ]
  });

  fs.writeFileSync(path.join(process.cwd(), ".dockerignore"), content);
}

try {
  action();
} catch (error) {
  core.setFailed(error);
}
